### Localhost/Books

###Get all books
GET http://localhost:3000/books

####Get books by id
GET http://localhost:3000/books/67017b3074983a380e2a2238 HTTP/1.1

####Create books
POST http://localhost:3000/books HTTP/1.1

content-type: application/json
    {
        "title":"To Kill a Mockingbird",
        "author":"Harper Lee",
        "year":"1960",
        "genre":"Fiction",
        "isbn":"9780446310789"
    }

####Update books
PUT  http://localhost:3000/books HTTP/1.1

content-type: application/json
    {
        "title":"any",
        "author":"any",
        "year":"any",
        "genre":"any",
        "isbn":"any"
    }

###Delete books
DELETE http://localhost:3000/books HTTP/1.1


### Production

###Get all books
GET https://books-eeav.onrender.com/books/ HTTP/1.1

###Get books by id
GET https://books-eeav.onrender.com/books/67017b3074983a380e2a2238' HTTP/1.1

####Create books
POST https://books-eeav.onrender.com/books HTTP/1.1
content-type: application/json

{
  "title": "Amyr",
  "author": "Ana",
  "year": "1456",
  "genre": "romance",
  "isbn": "8965786"
}

### Update books
PUT books-eeav.onrender.com/books/6701b6104e0316fb0917d205'

content-type: application/json
{
  "title": "Amyr",
  "author": "Ana",
  "year": "1456",
  "genre": "romance",
  "isbn": "8965786"
}

### Delete books
DELETE books-eeav.onrender.com/books/6701b6104e0316fb0917d205 HTTP/1.1

### Localhost/readers

### Get all readers
GET http://localhost:3000/readers HTTP/1.1

### Get one reader
GET http://localhost:3000/readers/67098f1045fa0e9d7a680410 HTTP/1.1

### Create reader
POST http://localhost:3000/readers HTTP/1.1
content-type: application/json
    {
        "readerId": 1,
        "name": "John Doe",
        "email": "john@example.com",
        "age": 30,
        "favoriteGenres": [
        "Fiction",
        "Romance"
        ],
        "membershipDate": "2024-10-01",
        "telephone": "+1234567890"
    }

### Update reader
PUT http://localhost:3000/readers/67098f1045fa0e9d7a680410 HTTP/1.1
content-type: application/json
    {
        "readerId": 1,
        "name": "John Doe",
        "email": "john@example.com",
        "age": 30,
        "favoriteGenres": [
        "Fiction",
        "Romance"
        ],
        "membershipDate": "2024-10-01",
        "telephone": "+1234567890"
    }

### Delete reader
DELETE http://localhost:3000/readers/67098f1045fa0e9d7a680410 HTTP/1.1


### Production/readers

### Get all readers
GET http://books-eeav.onrender.com/readers HTTP/1.1

### Get one reader
GET http://books-eeav.onrender.com/readers/67098f1045fa0e9d7a680410 HTTP/1.1

### Create reader
POST http://books-eeav.onrender.com/readers HTTP/1.1
content-type: application/json
    {
        "readerId": 1,
        "name": "John Doe",
        "email": "john@example.com",
        "age": 30,
        "favoriteGenres": [
        "Fiction",
        "Romance"
        ],
        "membershipDate": "2024-10-01",
        "telephone": "+1234567890"
    }

### Update reader
PUT http://books-eeav.onrender.com/readers/67098f1045fa0e9d7a680410 HTTP/1.1
content-type: application/json
    {
        "readerId": 1,
        "name": "John Doe",
        "email": "john@example.com",
        "age": 30,
        "favoriteGenres": [
        "Fiction",
        "Romance"
        ],
        "membershipDate": "2024-10-01",
        "telephone": "+1234567890"
    }

### Delete reader
DELETE http://books-eeav.onrender.com/readers/67098f1045fa0e9d7a680410 HTTP/1.1