### Localhost

###Get all books
GET http://localhost:3000/books

####Get books by id
GET http://localhost:3000/books/67017b3074983a380e2a2238 HTTP/1.1

####Create books
POST http://localhost:3000/books HTTP/1.1

content-type: application/json
    {
        "title":"To Kill a Mockingbird",
        "author":"Harper Lee",
        "year":"1960",
        "genre":"Fiction",
        "isbn":"9780446310789"
    }

####Update books
PUT  http://localhost:3000/books HTTP/1.1

content-type: application/json
    {
        "title":"any",
        "author":"any",
        "year":"any",
        "genre":"any",
        "isbn":"any"
    }

###Delete books
DELETE http://localhost:3000/books HTTP/1.1


### Production

###Get all books
GET https://books-eeav.onrender.com/books/ HTTP/1.1

###Get books by id
GET https://books-eeav.onrender.com/books/67017b3074983a380e2a2238' HTTP/1.1

####Create books

POST url HTTP/1.1
header name: header value

content